apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/kyverno/charts/kyverno
  contents:
  - path: .
    git:
      url: https://github.com/giantswarm/kyverno-upstream
      ref: v1.11.0
    includePaths:
      - charts/kyverno/charts/**
    newRootPath: manifests/crds
