apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/kyverno-crds/charts/crds
  contents:
  - path: .
    git:
      url: https://github.com/giantswarm/kyverno-upstream
      ref: v1.14.1
    includePaths:
      - charts/kyverno/charts/crds/**
    newRootPath: charts/kyverno/charts/crds/
