apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: manifests/crds
  contents:
  - path: .
    git:
      url: https://github.com/giantswarm/kyverno-upstream
      ref: v1.11.4
    includePaths:
      - charts/kyverno/charts/crds/templates/**
    newRootPath: charts/kyverno/charts/crds/templates
