{{/*
We have to create individual configmaps for each CRD - they exceed the total
allowed length for a configmap if they are combined.
*/}}
{{ $currentScope := . }}
{{- range $path, $_ := .Files.Glob "crd/**" }}
  {{- with $currentScope }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $path | base | trimSuffix ".yaml" }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  content: |
{{ .Files.Get $path | indent 4 }}
  {{- end }}
{{- end }}
