name: kyverno-crds
serviceType: managed

global:
  image:
    registry: gsoci.azurecr.io

image:
  registry: gsoci.azurecr.io
  repository: giantswarm/kubectl
  tag: '1.28.5'
  pullPolicy: IfNotPresent

# Pod securityContext
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault

# Container securityContext
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

resources:
  requests:
    cpu: 100m
    memory: 220Mi
  limits:
    cpu: 100m
    memory: 220Mi
