name: kyverno-crds
serviceType: managed

crds:
  groups:
    # -- Install CRDs in group `kyverno.io`
    # -- This field can be overwritten by setting crds.labels in the parent chart
    kyverno:
      cleanuppolicies: true
      clustercleanuppolicies: true
      clusterpolicies: true
      globalcontextentries: true
      policies: true
      policyexceptions: true
      updaterequests: true

    # -- Install CRDs in group `reports.kyverno.io`
    policies:
      validatingpolicies: true
      imagevalidatingpolicies: true
      policyexceptions: true

    # -- This field can be overwritten by setting crds.labels in the parent chart
    reports:
      clusterephemeralreports: true
      ephemeralreports: true

    # -- Install CRDs in group `wgpolicyk8s.io`
    # -- This field can be overwritten by setting crds.labels in the parent chart
    wgpolicyk8s:
      clusterpolicyreports: true
      policyreports: true

  annotations:
    helm.sh/resource-policy: keep

  customLabels: {}
