name: Sync from fork

on:
  schedule:
    - cron: '0 8 */7 * *' # At 08:00 on every 7th day-of-month

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  kyverno_fork_repo: https://github.com/giantswarm/kyverno-upstream
  branch: 'main#update-chart'

jobs:
  sync-app-kyverno-with-fork:
    runs-on: ubuntu-latest
    name: Update tag
    outputs:
      tag: ${{ steps.output_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          # Get the last tag from fork repo
          KYVERNO_LAST_TAG=$(git ls-remote --tags --sort='v:refname' --refs $kyverno_fork_repo \
           | tail -1 | cut -d '/' -f3)
          echo "Kyverno last tag found is $KYVERNO_LAST_TAG"

          # Setup git config
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git checkout -b $branch

          # Modify the version in Vendir config
          sed -i "/kyverno/{n;s/ref: .*/ref: $KYVERNO_LAST_TAG/}" vendir.yml
          git add vendir.yml
          git commit -m "Update app version from fork repo"
          git push origin $branch

          echo "tag=${KYVERNO_LAST_TAG}" >> $GITHUB_OUTPUT
  call-update-chart:
    uses: ./.github/workflows/zz_generated.update_chart.yaml
    needs: sync-app-kyverno-with-fork
    secrets: inherit
    with:
      branch: 'main#update-chart'
