name: Sync from fork

on:
  schedule:
    - cron: '0 8 */7 * *' # At 08:00 on every 7th day-of-month

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  kyverno_fork_repo: https://github.com/giantswarm/kyverno-upstream
  branch: 'main#update-chart'

jobs:
  sync-app-kyverno-with-fork:
    runs-on: ubuntu-latest
    name: Update tag
    outputs:
      tag: ${{ steps.output_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          # Get the last tag from fork repo
          KYVERNO_LAST_TAG=$(git ls-remote --tags --sort='v:refname' --refs $kyverno_fork_repo \
           | tail -1 | cut -d '/' -f3)
          echo "Kyverno last tag found is $KYVERNO_LAST_TAG"

          # Setup git config
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git checkout -b $branch

          # Modify the version in Vendir config
          sed -i "/kyverno/{n;s/ref: .*/ref: $KYVERNO_LAST_TAG/}" vendir.yml
          git add vendir.yml
          git commit -m "Update app version from fork repo"
          git push origin $branch

          echo "tag=${KYVERNO_LAST_TAG}" >> $GITHUB_OUTPUT
  call-update-chart:
    uses: ./.github/workflows/zz_generated.update_chart.yaml
    needs: sync-app-kyverno-with-fork
    with:
      branch: 'main#update-chart'
  copy-kyverno-crds:
    runs-on: ubuntu-latest
    needs: 
    - call-update-chart
    - sync-app-kyverno-with-fork
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main#update-chart'
      - name: Remove previous CRDs and install new ones
        run: |
          cd helm/kyverno-crds/crd

          # Remove previous CRDs
          git rm -f *.yaml
          
          # Move new CRDs to crd directory
          cp ../../../manifests/crds/crds.yaml .

          # Remove helm content from CRDs
          APP_VERSION=${{ needs.sync-app-kyverno-with-fork.outputs.tag }}
          sed -i -e "s/{{.Chart.AppVersion}}/$APP_VERSION/g" crds.yaml
          sed -i -e "/{{/d" crds.yaml

          # Add labels
          yq -i '.metadata.labels = {"app.kubernetes.io/name": "kyverno", "app.kubernetes.io/part-of": "kyverno", "app.kubernetes.io/version": env(APP_VERSION)}' crds.yaml

          # Split CRDs into multiple files
          yq -s '"crd-" + $index + ".yaml"' crds.yaml

          # Remove original file
          rm -f crds.yaml

          # Setup git config
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Commit and push
          git add .
          git commit -m "Update CRDs"
          git push origin 'main#update-chart'
